version: '3'

volumes:
  model-data:

services:
  api:
    image: rip-current-detection:latest
    build:
      context:      .
      dockerfile:   Dockerfile
    ports:
     - 8888:8000
    tmpfs:
     - "/outputs"
    environment:
     - OUTPUT_DIRECTORY=/outputs
    volumes:
      - "model-data:/root/.cache/torch:rw"
    command: >
      gunicorn api:app
        --bind "0.0.0.0:8000"
        --timeout 240
        -w 1 --max-requests 100
        -k uvicorn.workers.UvicornWorker
