name: rip_current_detection
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.9
  # Model/ML-related
  - numpy=1.23.3
  - opencv=4.6.0
  - pytorch=1.13.1
  - torchvision=0.14.1
  # TODO: matplotlib may be unused
  # - matplotlib=3.8.2
  # API related
  - fastapi
  - gunicorn
  - python-multipart
  - uvicorn
  - filetype
  # TODO: PIL/Pillow may be unused?
  # - Pillow==9.4.0
  # Testing/code quality
  - flake8>=3.7.9
  # Pip
  - pip
  - pip:
    - starlette_exporter>=0.21.0,<0.22