name: rip_current_detection
channels:
  # - pytorch
  # - nvidia
  - conda-forge
  - defaults
dependencies:
  # Python
  - conda-forge::python=3.9
  # Model/ML-related
  - conda-forge::numpy=1.23.3
  - conda-forge::opencv=4.6.0
  # - pytorch::pytorch=1.13.1
  # - pytorch::pytorch-cuda=12.1
  # - pytorch::torchvision=0.14.1
  # TODO: matplotlib may be unused
  # - matplotlib=3.8.2
  # API related
  - conda-forge::fastapi
  - conda-forge::gunicorn
  - conda-forge::python-multipart
  - conda-forge::uvicorn
  - conda-forge::filetype
  # TODO: PIL/Pillow may be unused?
  # - Pillow==9.4.0
  # Testing/code quality
  - conda-forge::flake8>=3.7.9
  # Pip
  - conda-forge::pip
  - pip:
    - starlette_exporter>=0.21.0,<0.22
    - torch==1.12 --index-url https://download.pytorch.org/whl/cu115
    - torchvision==0.13.0 --index-url https://download.pytorch.org/whl/cu115